### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by ishmaelen** [sipcapture/statstrmr#1]
Hello,

While running on rtplog (created by rtpsniff) I ocasionally see statstrmr crashing with output below.

SyntaxError: Unexpected token l
    at Object.parse (native)
    at ReadStream.<anonymous> (/usr/local/src/statstrmr/statstrmr.js:86:22)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1743:12)
    at FSReqWrap.wrapper [as oncomplete](fs.js:576:17)

**Comment by lmangani** [comment]
Thanks for your report!
I added error handling for the json parsing function please re-test with fa492cd

**Comment by ishmaelen** [comment]
Thanks! [fa492cd](https://github.com/sipcapture/statstrmr/commit/fa492cdbbd58ea1066cb8bdc12fb81e0b1a9a277) confirmed and issue #1 is fixed! :+1:
